# Generated by Django 2.0.6 on 2020-04-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuclass',
            name='stuclassid',
            field=models.IntegerField(null=True),
        ),
    ]
